# Install dependencies only when needed
FROM node:16-alpine AS deps

ARG NEXT_PUBLIC_APP_NAME=App
ARG NEXT_PUBLIC_APP_DESCRIPTION=Development
ARG NEXT_PUBLIC_APP_URL=/
ARG NEXT_PUBLIC_PLAUSIBLE_ENABLED
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ARG NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ARG NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ARG NEXT_PUBLIC_BANNER_MESSAGE
ARG NEXT_PUBLIC_HEADER_TITLE
ARG NEXT_PUBLIC_HEADER_ROUTES
ARG NEXT_PUBLIC_FOOTER_TITLE
ARG NEXT_PUBLIC_FOOTER_ROUTES

ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_PLAUSIBLE_ENABLED=$NEXT_PUBLIC_PLAUSIBLE_ENABLED
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS=$NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ENV NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED=$NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ENV NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST=$NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ENV NEXT_PUBLIC_BANNER_MESSAGE=$NEXT_PUBLIC_BANNER_MESSAGE
ENV NEXT_PUBLIC_HEADER_TITLE=$NEXT_PUBLIC_HEADER_TITLE
ENV NEXT_PUBLIC_HEADER_ROUTES=$NEXT_PUBLIC_HEADER_ROUTES
ENV NEXT_PUBLIC_FOOTER_TITLE=$NEXT_PUBLIC_FOOTER_TITLE
ENV NEXT_PUBLIC_FOOTER_ROUTES=$NEXT_PUBLIC_FOOTER_ROUTES

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM node:16-alpine AS builder

ARG NEXT_PUBLIC_APP_NAME=App
ARG NEXT_PUBLIC_APP_DESCRIPTION=Development
ARG NEXT_PUBLIC_APP_URL=/
ARG NEXT_PUBLIC_PLAUSIBLE_ENABLED
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ARG NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ARG NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ARG NEXT_PUBLIC_BANNER_MESSAGE
ARG NEXT_PUBLIC_HEADER_TITLE
ARG NEXT_PUBLIC_HEADER_ROUTES
ARG NEXT_PUBLIC_FOOTER_TITLE
ARG NEXT_PUBLIC_FOOTER_ROUTES

ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_PLAUSIBLE_ENABLED=$NEXT_PUBLIC_PLAUSIBLE_ENABLED
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS=$NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ENV NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED=$NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ENV NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST=$NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ENV NEXT_PUBLIC_BANNER_MESSAGE=$NEXT_PUBLIC_BANNER_MESSAGE
ENV NEXT_PUBLIC_HEADER_TITLE=$NEXT_PUBLIC_HEADER_TITLE
ENV NEXT_PUBLIC_HEADER_ROUTES=$NEXT_PUBLIC_HEADER_ROUTES
ENV NEXT_PUBLIC_FOOTER_TITLE=$NEXT_PUBLIC_FOOTER_TITLE
ENV NEXT_PUBLIC_FOOTER_ROUTES=$NEXT_PUBLIC_FOOTER_ROUTES

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner

ARG NEXT_PUBLIC_APP_NAME=App
ARG NEXT_PUBLIC_APP_DESCRIPTION=Development
ARG NEXT_PUBLIC_APP_URL=/
ARG NEXT_PUBLIC_PLAUSIBLE_ENABLED
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ARG NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ARG NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ARG NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ARG NEXT_PUBLIC_BANNER_MESSAGE
ARG NEXT_PUBLIC_HEADER_TITLE
ARG NEXT_PUBLIC_HEADER_ROUTES
ARG NEXT_PUBLIC_FOOTER_TITLE
ARG NEXT_PUBLIC_FOOTER_ROUTES

ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_PLAUSIBLE_ENABLED=$NEXT_PUBLIC_PLAUSIBLE_ENABLED
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS=$NEXT_PUBLIC_PLAUSIBLE_TRACK_OUTBOUND_LINKS
ENV NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED=$NEXT_PUBLIC_PLAUSIBLE_SELF_HOSTED
ENV NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN=$NEXT_PUBLIC_PLAUSIBLE_CUSTOM_DOMAIN
ENV NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST=$NEXT_PUBLIC_PLAUSIBLE_TRACK_LOCALHOST
ENV NEXT_PUBLIC_BANNER_MESSAGE=$NEXT_PUBLIC_BANNER_MESSAGE
ENV NEXT_PUBLIC_HEADER_TITLE=$NEXT_PUBLIC_HEADER_TITLE
ENV NEXT_PUBLIC_HEADER_ROUTES=$NEXT_PUBLIC_HEADER_ROUTES
ENV NEXT_PUBLIC_FOOTER_TITLE=$NEXT_PUBLIC_FOOTER_TITLE
ENV NEXT_PUBLIC_FOOTER_ROUTES=$NEXT_PUBLIC_FOOTER_ROUTES

WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]